### ISSUE TITLE
Auth passthrough for premium users

### ISSUE THREAD

**Issue by Carlosjrlu** [yushijinhun/authlib-injector#138]
Hello, I would like to ask if it is possible to passthrough all the logins from premium users to mojang servers for login, and still use the authlib server for non-premium users.

If this has been asked before, I would like to apologize as I couldn't find anything in this topic as my primary language is not chinese, not even english.

**Comment by August7** [comment]
> Hello, I would like to ask if it is possible to passthrough all the logins from premium users to mojang servers for login, and still use the authlib server for non-premium users.
> 
> If this has been asked before, I would like to apologize as I couldn't find anything in this topic as my primary language is not chinese, not even english.

Try to use [YggdrasilOfficialProxy](https://github.com/YggdrasilOfficialProxy/YggdrasilOfficialProxy) or [MultiLogin](https://github.com/CaaMoe/MultiLogin)

**Comment by yushijinhun** [comment]
This is a non-goal for authlib-injector, because it would cause problems that are technically unavoidable. For example, it is impossible to make premium users see custom capes, because thier clients are unmodified. (you can use mineskin.org, but this only works with skins)

As is said by @August7, you can use https://github.com/CaaMoe/MultiLogin on the server side, if you really want to do this. (although I do not recommend this)
