### ISSUE TITLE
[广告]帮助在面板服使用authlib-injector的辅助工具LaunchHelper

### ISSUE THREAD

**Issue by inactive-virus** [yushijinhun/authlib-injector#62]
## LaunchHelper

国内的面板服几乎都是Multicraft面板，它能使用自定义服务端（如果商家允许的话），但不能自定义启动参数，所以平时无法使用authlib-injector。

LaunchHelper的Jar可以实现不添加任何命令行参数载入Java agent并启动另一个可执行Jar，从而解决了在Multicraft面板服使用authlib-injector的难题。

仓库地址：[Codex-in-somnio/LaunchHelper](https://github.com/Codex-in-somnio/LaunchHelper)

这个轮子刚刚能转，欢迎大家前来吃🦀

**Comment by inactive-virus** [comment]
目前在酷牛和icraft两家面板测试过，均可使用

**Comment by yushijinhun** [comment]
感谢您的工作，我已将此 issue 设置为 pinned。

**Comment by AllenBlockChicken** [comment]
旋律云Multicraft面板服，一打开服务器就会崩溃，是配置的问题吗？配置是2h4g，服务端CatServer1.12.2，就大佬帮忙QAQ

**Comment by Lama3L9R** [comment]
@AllenBlockChicken 这边建议发一下报错日志

**Comment by AllenBlockChicken** [comment]
> @AllenBlockChicken 这边建议发一下报错日志
以下是报错日志，如果能帮忙解决的话就真的是太感谢了
12.11 19:10:36 [面板] 收到启动命令
12.11 19:10:36 [面板] 加载服务器属性
12.11 19:10:36 [面板] 开启服务器!
12.11 19:10:36 [面板] 加载配置： "[高级Java8][优化参数]自定义核心 请查看帮助中心使用说明 核心上传到主目录 改名java1.8.jar"
12.11 19:10:36 [面板] Updating eula.txt file
12.11 19:10:38 [服务器] 信息 [LH] 
12.11 19:10:38 [服务器] 信息 [LH]     //       ////   //  //  //  //   /////  //  //
12.11 19:10:38 [服务器] 信息 [LH]    //      //  //  //  //  /// //  //      //  //  ___
12.11 19:10:38 [服务器] 信息 [LH]   //      //////  //  //  // ///  //      //////  ____
12.11 19:10:38 [服务器] 信息 [LH]  //      //  //  //  //  //  //  //      //  //  _____
12.11 19:10:38 [服务器] 信息 [LH] //////  //  //   ////   //  //   /////  //  //  ______
12.11 19:10:38 [服务器] 信息 [LH] 
12.11 19:10:38 [服务器] 信息 [LH]       //  //  //////  //      /////   //////  /////
12.11 19:10:38 [服务器] 信息 [LH]      //  //  //      //      //  //  //      //  //  ___
12.11 19:10:38 [服务器] 信息 [LH]     //////  /////   //      /////   /////   /////   ____
12.11 19:10:38 [服务器] 信息 [LH]    //  //  //      //      //      //      //  //  _____
12.11 19:10:38 [服务器] 信息 [LH]   //  //  //////  //////  //      //////  //  //  ______
12.11 19:10:38 [服务器] 信息 [LH] 
12.11 19:10:38 [服务器] 信息 [LH] ====================================================
12.11 19:10:38 [服务器] 信息 [LH] LaunchHelper (0.1) Created with ♥ by Codex in Somnio
12.11 19:10:38 [服务器] 信息 [LH] https://github.com/Codex-in-somnio/LaunchHelper
12.11 19:10:38 [服务器] 信息 [LH] ====================================================
12.11 19:10:38 [服务器] 信息 [LH] 
12.11 19:10:38 [服务器] 信息 [LH] Loading executable Jar CatServer-1.12.2.jar
12.11 19:10:38 [服务器] 信息 [LH] Loading Java agent authlib-injector-1.2.1.jar=https://littleskin.cn/api/yggdrasil
12.11 19:10:38 [服务器] 信息 [authlib-injector] [INFO] Logging file: /authlib-injector.log
12.11 19:10:38 [服务器] 信息 [authlib-injector] [INFO] Launched from agentmain
12.11 19:10:38 [服务器] 信息 [authlib-injector] [INFO] Version: 1.2.1
12.11 19:10:38 [服务器] 信息 [authlib-injector] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil
12.11 19:10:39 [服务器] 信息 [authlib-injector] [INFO] Attempt to retransform all classes
12.11 19:10:39 [服务器] 信息 [authlib-injector] [INFO] Retransformed 44 classes in 52ms
12.11 19:10:39 [服务器] 信息 加载Lib库，请稍等...
12.11 19:10:39 [服务器] 信息 2022-11-12 11:10:39,838 main WARN Disabling terminal, you're running in an unsupported environment.
12.11 19:10:39 [服务器] main/信息 Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
12.11 19:10:39 [服务器] main/信息 Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
12.11 19:10:39 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
12.11 19:10:39 [服务器] main/信息 Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
12.11 19:10:39 [服务器] main/信息 Java is OpenJDK 64-Bit Server VM, version 1.8.0_111, running on Linux:amd64:5.4.209-1.el7.elrepo.x86_64, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
12.11 19:10:40 [服务器] main/WARN The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
12.11 19:10:40 [服务器] main/WARN The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
12.11 19:10:40 [服务器] main/WARN The coremod CatCorePlugin (catserver.server.CatCorePlugin) is not signed!
12.11 19:10:40 [服务器] main/信息 Searching /./mods for mods
12.11 19:10:40 [服务器] main/信息 Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
12.11 19:10:40 [服务器] main/信息 Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
12.11 19:10:40 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
12.11 19:10:40 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
12.11 19:10:40 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
12.11 19:10:42 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
12.11 19:10:42 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
12.11 19:10:42 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
12.11 19:10:42 [服务器] main/信息 Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
12.11 19:10:42 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
12.11 19:10:42 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
12.11 19:10:43 [服务器] main/信息 Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
12.11 19:10:47 [服务器] 信息 [authlib-injector] [INFO] Httpd is running on port 34621
12.11 19:10:47 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
12.11 19:10:47 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
12.11 19:10:47 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Constant URL Transformer]
12.11 19:10:47 [服务器] 服务器 thread/信息 开启Minecraft服务器版本: 1.12.2
12.11 19:10:47 [服务器] Server console handler/WARN Exception in thread "Server console handler" 
12.11 19:10:47 [服务器] Server console handler/WARN java.lang.NoClassDefFoundError: org/jline/reader/EndOfFileException
12.11 19:10:47 [服务器] Server console handler/WARN at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:114)
12.11 19:10:47 [服务器] Server console handler/WARN Caused by: java.lang.ClassNotFoundException: org.jline.reader.EndOfFileException
12.11 19:10:47 [服务器] Server console handler/WARN at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
12.11 19:10:47 [服务器] Server console handler/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
12.11 19:10:47 [服务器] Server console handler/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
12.11 19:10:47 [服务器] Server console handler/WARN at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
12.11 19:10:47 [服务器] Server console handler/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
12.11 19:10:47 [服务器] Server console handler/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
12.11 19:10:47 [服务器] Server console handler/WARN ... 1 more
12.11 19:10:47 [服务器] 服务器 thread/信息 MinecraftForge v14.23.5.2860 Initialized
12.11 19:10:47 [服务器] 服务器 thread/信息 Starts to replace vanilla recipe ingredients with ore ingredients.
12.11 19:10:47 [服务器] 服务器 thread/信息 Invalid recipe found with multiple oredict ingredients in the same ingredient...
12.11 19:10:47 [服务器] 服务器 thread/信息 Replaced 1227 ore ingredients
12.11 19:10:47 [服务器] 服务器 thread/信息 服务器关闭中
12.11 19:10:47 [服务器] 服务器 thread/信息 Saving worlds
12.11 19:10:47 [服务器] 服务器 thread/WARN Exception in thread "Server thread" 
12.11 19:10:47 [服务器] 服务器 thread/WARN java.lang.NullPointerException
12.11 19:10:47 [服务器] 服务器 thread/WARN at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:852)
12.11 19:10:47 [服务器] 服务器 thread/WARN at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:514)
12.11 19:10:47 [服务器] 服务器 thread/WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:751)
12.11 19:10:47 [服务器] 服务器 thread/WARN at java.lang.Thread.run(Thread.java:745)
12.11 19:10:53 [面板] 收到停止命令
12.11 19:10:53 [面板] 停止服务器!
12.11 19:11:55 [面板] Terminating server via signal
12.11 19:11:56 [面板] 服务器停止 (terminating)
12.11 19:11:56 [面板] 查看奔溃记录，检查服务器控制台. Return value: 143
12.11 19:11:56 [面板] 服务器已经关闭

**Comment by AllenBlockChicken** [comment]
@Lama3L9R 以下是报错日志，如果能帮忙解决的话就太感谢了
12.11 19:10:36 [面板] 收到启动命令
12.11 19:10:36 [面板] 加载服务器属性
12.11 19:10:36 [面板] 开启服务器!
12.11 19:10:36 [面板] 加载配置： "[高级Java8][优化参数]自定义核心 请查看帮助中心使用说明 核心上传到主目录 改名java1.8.jar"
12.11 19:10:36 [面板] Updating eula.txt file
12.11 19:10:38 [服务器] 信息 [LH] 
12.11 19:10:38 [服务器] 信息 [LH]     //       ////   //  //  //  //   /////  //  //
12.11 19:10:38 [服务器] 信息 [LH]    //      //  //  //  //  /// //  //      //  //  ___
12.11 19:10:38 [服务器] 信息 [LH]   //      //////  //  //  // ///  //      //////  ____
12.11 19:10:38 [服务器] 信息 [LH]  //      //  //  //  //  //  //  //      //  //  _____
12.11 19:10:38 [服务器] 信息 [LH] //////  //  //   ////   //  //   /////  //  //  ______
12.11 19:10:38 [服务器] 信息 [LH] 
12.11 19:10:38 [服务器] 信息 [LH]       //  //  //////  //      /////   //////  /////
12.11 19:10:38 [服务器] 信息 [LH]      //  //  //      //      //  //  //      //  //  ___
12.11 19:10:38 [服务器] 信息 [LH]     //////  /////   //      /////   /////   /////   ____
12.11 19:10:38 [服务器] 信息 [LH]    //  //  //      //      //      //      //  //  _____
12.11 19:10:38 [服务器] 信息 [LH]   //  //  //////  //////  //      //////  //  //  ______
12.11 19:10:38 [服务器] 信息 [LH] 
12.11 19:10:38 [服务器] 信息 [LH] ====================================================
12.11 19:10:38 [服务器] 信息 [LH] LaunchHelper (0.1) Created with ♥ by Codex in Somnio
12.11 19:10:38 [服务器] 信息 [LH] https://github.com/Codex-in-somnio/LaunchHelper
12.11 19:10:38 [服务器] 信息 [LH] ====================================================
12.11 19:10:38 [服务器] 信息 [LH] 
12.11 19:10:38 [服务器] 信息 [LH] Loading executable Jar CatServer-1.12.2.jar
12.11 19:10:38 [服务器] 信息 [LH] Loading Java agent authlib-injector-1.2.1.jar=https://littleskin.cn/api/yggdrasil
12.11 19:10:38 [服务器] 信息 [authlib-injector] [INFO] Logging file: /authlib-injector.log
12.11 19:10:38 [服务器] 信息 [authlib-injector] [INFO] Launched from agentmain
12.11 19:10:38 [服务器] 信息 [authlib-injector] [INFO] Version: 1.2.1
12.11 19:10:38 [服务器] 信息 [authlib-injector] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil
12.11 19:10:39 [服务器] 信息 [authlib-injector] [INFO] Attempt to retransform all classes
12.11 19:10:39 [服务器] 信息 [authlib-injector] [INFO] Retransformed 44 classes in 52ms
12.11 19:10:39 [服务器] 信息 加载Lib库，请稍等...
12.11 19:10:39 [服务器] 信息 2022-11-12 11:10:39,838 main WARN Disabling terminal, you're running in an unsupported environment.
12.11 19:10:39 [服务器] main/信息 Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
12.11 19:10:39 [服务器] main/信息 Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
12.11 19:10:39 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
12.11 19:10:39 [服务器] main/信息 Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
12.11 19:10:39 [服务器] main/信息 Java is OpenJDK 64-Bit Server VM, version 1.8.0_111, running on Linux:amd64:5.4.209-1.el7.elrepo.x86_64, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
12.11 19:10:40 [服务器] main/WARN The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
12.11 19:10:40 [服务器] main/WARN The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
12.11 19:10:40 [服务器] main/WARN The coremod CatCorePlugin (catserver.server.CatCorePlugin) is not signed!
12.11 19:10:40 [服务器] main/信息 Searching /./mods for mods
12.11 19:10:40 [服务器] main/信息 Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
12.11 19:10:40 [服务器] main/信息 Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
12.11 19:10:40 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
12.11 19:10:40 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
12.11 19:10:40 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
12.11 19:10:42 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
12.11 19:10:42 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
12.11 19:10:42 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
12.11 19:10:42 [服务器] main/信息 Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
12.11 19:10:42 [服务器] main/信息 Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
12.11 19:10:42 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
12.11 19:10:43 [服务器] main/信息 Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
12.11 19:10:47 [服务器] 信息 [authlib-injector] [INFO] Httpd is running on port 34621
12.11 19:10:47 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
12.11 19:10:47 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
12.11 19:10:47 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Constant URL Transformer]
12.11 19:10:47 [服务器] 服务器 thread/信息 开启Minecraft服务器版本: 1.12.2
12.11 19:10:47 [服务器] Server console handler/WARN Exception in thread "Server console handler" 
12.11 19:10:47 [服务器] Server console handler/WARN java.lang.NoClassDefFoundError: org/jline/reader/EndOfFileException
12.11 19:10:47 [服务器] Server console handler/WARN at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:114)
12.11 19:10:47 [服务器] Server console handler/WARN Caused by: java.lang.ClassNotFoundException: org.jline.reader.EndOfFileException
12.11 19:10:47 [服务器] Server console handler/WARN at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
12.11 19:10:47 [服务器] Server console handler/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
12.11 19:10:47 [服务器] Server console handler/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
12.11 19:10:47 [服务器] Server console handler/WARN at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
12.11 19:10:47 [服务器] Server console handler/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
12.11 19:10:47 [服务器] Server console handler/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
12.11 19:10:47 [服务器] Server console handler/WARN ... 1 more
12.11 19:10:47 [服务器] 服务器 thread/信息 MinecraftForge v14.23.5.2860 Initialized
12.11 19:10:47 [服务器] 服务器 thread/信息 Starts to replace vanilla recipe ingredients with ore ingredients.
12.11 19:10:47 [服务器] 服务器 thread/信息 Invalid recipe found with multiple oredict ingredients in the same ingredient...
12.11 19:10:47 [服务器] 服务器 thread/信息 Replaced 1227 ore ingredients
12.11 19:10:47 [服务器] 服务器 thread/信息 服务器关闭中
12.11 19:10:47 [服务器] 服务器 thread/信息 Saving worlds
12.11 19:10:47 [服务器] 服务器 thread/WARN Exception in thread "Server thread" 
12.11 19:10:47 [服务器] 服务器 thread/WARN java.lang.NullPointerException
12.11 19:10:47 [服务器] 服务器 thread/WARN at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:852)
12.11 19:10:47 [服务器] 服务器 thread/WARN at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:514)
12.11 19:10:47 [服务器] 服务器 thread/WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:751)
12.11 19:10:47 [服务器] 服务器 thread/WARN at java.lang.Thread.run(Thread.java:745)
12.11 19:10:53 [面板] 收到停止命令
12.11 19:10:53 [面板] 停止服务器!
12.11 19:11:55 [面板] Terminating server via signal
12.11 19:11:56 [面板] 服务器停止 (terminating)
12.11 19:11:56 [面板] 查看奔溃记录，检查服务器控制台. Return value: 143
12.11 19:11:56 [面板] 服务器已经关闭
